quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=labcom,2015
quarkus.datasource.jdbc.url=jdbc:postgresql://dbserver:5432/distribuidaclases

#quarkus.hibernate-orm.log.sql=true
#quarkus.hibernate-orm.show-sql=true
#quarkus.hibernate-orm.log.format-sql=true
#quarkus.hibernate-orm.database.generation=update

#quarkus.flyway.clean-at-start=true

quarkus.flyway.baseline-at-start=true
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=classpath:db/migration

quarkus.http.port=8080

#configuracion consul
consul.host=127.0.0.1
consul.port=8500




